[package]
name = "charging_model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
rand = "0.8.5"

[dev-dependencies]
env_logger = "*"
test-log = "0.2.12"
